module.exports = function (i18n) {
    const _ = i18n._;
    return {
        "keywords": {
            "planet": [_("planetz", "cosmos_keywords")],
            "planete": [_("planete", "cosmos_keywords")],
            "moon": [_("moon", "cosmos_keywords")],
            "asteroid": [_("moon", "cosmos_keywords")],
            "meteor": "meteor",
            "comet": [_("comete?", "cosmos_keywords")]
        },
        "planets": {
            "C(é|e)r(è|e)s": [_("C(é|e)r(è|e)s","cosmos_bodies")],
            "(É|E)ris": [_("(É|E)ris","cosmos_bodies")],
            "Uranus": [_("Uranus","cosmos_bodies")],
            "Pluton": [_("Pluto","cosmos_bodies")],
            "Neptune": [_("Neptune","cosmos_bodies")],
            "Haumea": [_("Haumea","cosmos_bodies")],
            "Makemake": [_("Makemake","cosmos_bodies")],
            "Jupiter": [_("Jupiter","cosmos_bodies")],
            "Mars": [_("Mars","cosmos_bodies")],
            "Mercure": [_("Mercury","cosmos_bodies")],
            "Saturne": [_("Saturn","cosmos_bodies")],
            "La Terre": [_("Earth","cosmos_bodies")],
            "V(é|e)nus": [_("Venus","cosmos_bodies")]
        },

          "moons": {

            "La Lune": [_("Moon","cosmos_bodies")],
            "Phobos": [_("Phobos","cosmos_bodies")],
            "Deïmos": [_("Deimos","cosmos_bodies")],
            "Io": [_("Io","cosmos_bodies")],
            "Europe": [_("Europa","cosmos_bodies")],
            "Ganym(è|e)de": [_("Ganymede","cosmos_bodies")],
            "Callisto": [_("Callisto","cosmos_bodies")],
            "Amalth(é|e)e": [_("Amalthea","cosmos_bodies")],
            "Himalia": [_("Himalia","cosmos_bodies")],
            "(É|E)lara": [_("Elara","cosmos_bodies")],
            "Pasipha(é|e)": [_("Pasiphae","cosmos_bodies")],
            "Sinop(é|e)": [_("Sinope","cosmos_bodies")],
            "Lysith(é|e)a": [_("Lysithea","cosmos_bodies")],
            "Carm(é|e)": [_("Carme","cosmos_bodies")],
            "Anank(é|e)": [_("Ananke","cosmos_bodies")],
            "L(é|e)da": [_("Leda","cosmos_bodies")],
            "Th(é|e)b(é|e)": [_("Thebe","cosmos_bodies")],
            "Adrast(é|e)e": [_("Adrastea","cosmos_bodies")],
            "M(é|e)tis": [_("Metis","cosmos_bodies")],
            "Callirrho(é|e)": [_("Callirrhoe ","cosmos_bodies")],
            "Th(é|e)misto ": [_("Themisto ","cosmos_bodies")],
            "M(é|e)gaclit(é|e)": [_("Megaclite ","cosmos_bodies")],
            "Tayg(é|e)t(é|e) ": [_("Taygete ","cosmos_bodies")],
            "Chald(é|e)n(é|e) ": [_("Chaldene ","cosmos_bodies")],
            "Harpalyk(é|e)": [_("Harpalyke ","cosmos_bodies")],
            "Kalyk(é|e)": [_("Kalyke ","cosmos_bodies")],
            "Iocast(é|e)": [_("Iocaste ","cosmos_bodies")],
            "Erinom(é|e)": [_("Erinome ","cosmos_bodies")],
            "Isono(é|e)": [_("Isonoe ","cosmos_bodies")],
            "Praxidyk(é|e)": [_("Praxidike ","cosmos_bodies")],
            "Autono(é|e)": [_("Autonoe ","cosmos_bodies")],
            "Thyon(é|e)": [_("Thyone ","cosmos_bodies")],
            "Hermipp(é|e)": [_("Hermippe ","cosmos_bodies")],
            "Aitn(é|e)": [_("Aitne ","cosmos_bodies")],
            "Eurydom(é|e)": [_("Eurydome ","cosmos_bodies")],
            "Euanth(é|e)": [_("Euanthe ","cosmos_bodies")],
            "Euporie ": [_("Euporie ","cosmos_bodies")],
            "Orthosie ": [_("Orthosie ","cosmos_bodies")],
            "Spond(é|e)": [_("Sponde ","cosmos_bodies")],
            "Cal(é|e)": [_("Kale ","cosmos_bodies")],
            "Pasith(é|e)e ": [_("Pasithee ","cosmos_bodies")],
            "H(é|e)g(é|e)mone ": [_("Hegemone ","cosmos_bodies")],
            "Mn(é|e)m(é|e)": [_("Mneme ","cosmos_bodies")],
            "Aoed(é|e)": [_("Aoede ","cosmos_bodies")],
            "Thelxino(é|e)": [_("Thelxinoe ","cosmos_bodies")],
            "Arch(é|e)": [_("Arche ","cosmos_bodies")],
            "Callichore ": [_("Kallichore ","cosmos_bodies")],
            "H(é|e)lic(é|e) ": [_("Helike ","cosmos_bodies")],
            "Carpo ": [_("Carpo ","cosmos_bodies")],
            "Euk(é|e)lad(é|e)": [_("Eukelade ","cosmos_bodies")],
            "Cyll(è|e)ne ": [_("Cyllene ","cosmos_bodies")],
            "Cor(é|e)": [_("Kore ","cosmos_bodies")],
            "Hers(é|e)": [_("Herse ","cosmos_bodies")],
            "S 2003 J2 ": [_("S 2003 J2 ","cosmos_bodies")],
            "S 2003 J3 ": [_("S 2003 J3 ","cosmos_bodies")],
            "S 2003 J4 ": [_("S 2003 J4 ","cosmos_bodies")],
            "S 2003 J5 ": [_("S 2003 J5 ","cosmos_bodies")],
            "S 2003 J9 ": [_("S 2003 J9 ","cosmos_bodies")],
            "S 2003 J10 ": [_("S 2003 J10 ","cosmos_bodies")],
            "S 2003 J12 ": [_("S 2003 J12 ","cosmos_bodies")],
            "S 2003 J15 ": [_("S 2003 J15 ","cosmos_bodies")],
            "S 2003 J16 ": [_("S 2003 J16 ","cosmos_bodies")],
            "S 2003 J18 ": [_("S 2003 J18 ","cosmos_bodies")],
            "S 2003 J19 ": [_("S 2003 J19 ","cosmos_bodies")],
            "S 2003 J23 ": [_("S 2003 J23 ","cosmos_bodies")],
            "Mimas": [_("Mimas","cosmos_bodies")],
            "Encelade": [_("Enceladus","cosmos_bodies")],
            "T(é|e)thys": [_("Tethys","cosmos_bodies")],
            "Dion(é|e)": [_("Dione","cosmos_bodies")],
            "Rh(é|e)a": [_("Rhea","cosmos_bodies")],
            "Titan": [_("Titan","cosmos_bodies")],
            "Hyp(é|e)rion": [_("Hyperion","cosmos_bodies")],
            "Japet": [_("Iapetus","cosmos_bodies")],
            "Phoeb(é|e)": [_("Phoebe","cosmos_bodies")],
            "Janus": [_("Janus","cosmos_bodies")],
            "Epim(é|e)th(é|e)e": [_("Epimetheus","cosmos_bodies")],
            "H(é|e)l(è|e)ne": [_("Helene","cosmos_bodies")],
            "T(é|e)lesto": [_("Telesto","cosmos_bodies")],
            "Calypso": [_("Calypso","cosmos_bodies")],
            "Atlas": [_("Atlas","cosmos_bodies")],
            "Prom(é|e)th(é|e)e": [_("Prometheus","cosmos_bodies")],
            "Pandore": [_("Pandora","cosmos_bodies")],
            "Pan": [_("Pan","cosmos_bodies")],
            "Ymir ": [_("Ymir ","cosmos_bodies")],
            "Paaliaq ": [_("Paaliaq ","cosmos_bodies")],
            "Tarvos ": [_("Tarvos ","cosmos_bodies")],
            "Ijiraq ": [_("Ijiraq ","cosmos_bodies")],
            "Suttungr ": [_("Suttungr ","cosmos_bodies")],
            "Kiviuq ": [_("Kiviuq ","cosmos_bodies")],
            "Mundilfari ": [_("Mundilfari ","cosmos_bodies")],
            "Albiorix ": [_("Albiorix ","cosmos_bodies")],
            "Skathi ": [_("Skathi ","cosmos_bodies")],
            "Erriapo": [_("Erriapus ","cosmos_bodies")],
            "Siarnaq ": [_("Siarnaq ","cosmos_bodies")],
            "Thrymr ": [_("Thrymr ","cosmos_bodies")],
            "Narvi ": [_("Narvi ","cosmos_bodies")],
            "M(é|e)thone ": [_("Methone ","cosmos_bodies")],
            "Pall(è|e)ne ": [_("Pallene ","cosmos_bodies")],
            "Pollux": [_("Polydeuces ","cosmos_bodies")],
            "Daphnis ": [_("Daphnis ","cosmos_bodies")],
            "Aegir ": [_("Aegir ","cosmos_bodies")],
            "Bebhionn ": [_("Bebhionn ","cosmos_bodies")],
            "Bergelmir ": [_("Bergelmir ","cosmos_bodies")],
            "Bestla ": [_("Bestla ","cosmos_bodies")],
            "Farbauti ": [_("Farbauti ","cosmos_bodies")],
            "Fenrir ": [_("Fenrir ","cosmos_bodies")],
            "Fornjot ": [_("Fornjot ","cosmos_bodies")],
            "Hati ": [_("Hati ","cosmos_bodies")],
            "Hyrrokkin ": [_("Hyrrokkin ","cosmos_bodies")],
            "Kari ": [_("Kari ","cosmos_bodies")],
            "Loge ": [_("Loge ","cosmos_bodies")],
            "Skoll ": [_("Skoll ","cosmos_bodies")],
            "Surtur ": [_("Surtur ","cosmos_bodies")],
            "Anth(é|e)": [_("Anthe ","cosmos_bodies")],
            "Jarnsaxa ": [_("Jarnsaxa ","cosmos_bodies")],
            "Greip ": [_("Greip ","cosmos_bodies")],
            "Tarqeq ": [_("Tarqeq ","cosmos_bodies")],
            "(É|E)g(é|e)on": [_("Aegaeon ","cosmos_bodies")],
            "S 2004 S7 ": [_("S 2004 S7 ","cosmos_bodies")],
            "S 2004 S12 ": [_("S 2004 S12 ","cosmos_bodies")],
            "S 2004 S13 ": [_("S 2004 S13 ","cosmos_bodies")],
            "S 2004 S17 ": [_("S 2004 S17 ","cosmos_bodies")],
            "S 2006 S1 ": [_("S 2006 S1 ","cosmos_bodies")],
            "S 2006 S3 ": [_("S 2006 S3 ","cosmos_bodies")],
            "S 2007 S2 ": [_("S 2007 S2 ","cosmos_bodies")],
            "S 2007 S3 ": [_("S 2007 S3 ","cosmos_bodies")],
            "S 2009 S1 ": [_("S 2009 S1 ","cosmos_bodies")],
            "Ariel": [_("Ariel","cosmos_bodies")],
            "Umbriel": [_("Umbriel","cosmos_bodies")],
            "Titania": [_("Titania","cosmos_bodies")],
            "Ob(é|e)ron": [_("Oberon","cosmos_bodies")],
            "Miranda": [_("Miranda","cosmos_bodies")],
            "Cord(é|e)lia": [_("Cordelia","cosmos_bodies")],
            "Oph(é|e)lie": [_("Ophelia","cosmos_bodies")],
            "Bianca": [_("Bianca","cosmos_bodies")],
            "Cressida": [_("Cressida","cosmos_bodies")],
            "Desd(é|e)mone": [_("Desdemona","cosmos_bodies")],
            "Juliette": [_("Juliet","cosmos_bodies")],
            "Portia": [_("Portia","cosmos_bodies")],
            "Rosalinde": [_("Rosalind","cosmos_bodies")],
            "Belinda": [_("Belinda","cosmos_bodies")],
            "Puck": [_("Puck","cosmos_bodies")],
            "Caliban": [_("Caliban","cosmos_bodies")],
            "Sycorax": [_("Sycorax","cosmos_bodies")],
            "Prospero": [_("Prospero","cosmos_bodies")],
            "Setebos": [_("Setebos","cosmos_bodies")],
            "Stephano": [_("Stephano","cosmos_bodies")],
            "Trinculo": [_("Trinculo","cosmos_bodies")],
            "Francisco": [_("Francisco","cosmos_bodies")],
            "Margaret": [_("Margaret","cosmos_bodies")],
            "Ferdinand": [_("Ferdinand","cosmos_bodies")],
            "Perdita": [_("Perdita","cosmos_bodies")],
            "Mab": [_("Mab","cosmos_bodies")],
            "Cupid": [_("Cupid","cosmos_bodies")],
            "Triton": [_("Triton","cosmos_bodies")],
            "N(é|e)reïde": [_("Nereid","cosmos_bodies")],
            "Naïade": [_("Naiad","cosmos_bodies")],
            "Thalassa": [_("Thalassa","cosmos_bodies")],
            "Despina": [_("Despina","cosmos_bodies")],
            "Galat(é|e)e": [_("Galatea","cosmos_bodies")],
            "Larissa": [_("Larissa","cosmos_bodies")],
            "Prot(é|e)e": [_("Proteus","cosmos_bodies")],
            "Halim(è|e)de": [_("Halimede","cosmos_bodies")],
            "Psamath(é|e)e": [_("Psamathe","cosmos_bodies")],
            "Sao": [_("Sao","cosmos_bodies")],
            "Laom(é|e)die": [_("Laomedeia","cosmos_bodies")],
            "N(é|e)so": [_("Neso","cosmos_bodies")],
            "Charon": [_("Charon","cosmos_bodies")],
            "Nix": [_("Nix","cosmos_bodies")],
            "Hydra": [_("Hydra","cosmos_bodies")],
            "Namaka": [_("Namaka","cosmos_bodies")],
            "Hi'iaka": [_("Hi'iaka","cosmos_bodies")],
            "Dysnomie": [_("Dysnomie","cosmos_bodies")],
            "Dia": [_("Dia","cosmos_bodies")],
            "S 2004 S3": [_("S 2004 S3","cosmos_bodies")],
            "S 2004 S4": [_("S 2004 S4","cosmos_bodies")],
            "S 2004 S6": [_("S 2004 S6","cosmos_bodies")],
            "S 2010 J1": [_("S 2010 J1","cosmos_bodies")],
            "S 2010 J2": [_("S 2010 J2","cosmos_bodies")],
            "Petit-Prince": [_("The Little Prince","cosmos_bodies")],
            "R(é|e)mus": [_("R(é|e)mus","cosmos_bodies")],
            "Vanth": [_("Vanth","cosmos_bodies")],
            "Dactyl": [_("Dactyl","cosmos_bodies")],
            "Romulus": [_("Romulus","cosmos_bodies")],
            "Alexhelios": [_("Alexhelios","cosmos_bodies")],
            "Cleoselene": [_("Cleoselene","cosmos_bodies")],
            "Weywot": [_("Weywot","cosmos_bodies")],
            "Kerberos": [_("Kerberos","cosmos_bodies")],
            "S 2011 J1": [_("S 2011 J1","cosmos_bodies")],
            "S 2011 J2": [_("S 2011 J2","cosmos_bodies")],
            "Styx": [_("Styx","cosmos_bodies")],
            "Hippocampe": [_("Hippocamp","cosmos_bodies")],
            "MK2": [_("MK2","cosmos_bodies")],
            "S 2017 J 1": [_("S 2017 J 1","cosmos_bodies")],
            "S 2016 J 1": [_("S 2016 J 1","cosmos_bodies")],
            "S 2016 J2 (Valetudo)": [_("S 2016 J2 (Valetudo)","cosmos_bodies")],
            "S 2017 J2": [_("S 2017 J2","cosmos_bodies")],
            "S 2017 J3": [_("S 2017 J3","cosmos_bodies")],
            "S 2017 J4": [_("S 2017 J4","cosmos_bodies")],
            "S 2017 J5": [_("S 2017 J5","cosmos_bodies")],
            "S 2017 J6": [_("S 2017 J6","cosmos_bodies")],
            "S 2017 J7": [_("S 2017 J7","cosmos_bodies")],
            "S 2017 J8": [_("S 2017 J8","cosmos_bodies")],
            "S 2017 J9": [_("S 2017 J9","cosmos_bodies")],
            "S 2018 J1": [_("S 2018 J1","cosmos_bodies")]
        },

        "others": {
            "H(é|e)b(é|e)": [_("H(é|e)b(é|e)","cosmos_bodies")],
            "1999 TC36": [_("1999 TC36","cosmos_bodies")],
            "Pulcova": [_("Pulcova","cosmos_bodies")],
            "Toutatis": [_("Toutatis","cosmos_bodies")],
            "Quaoar": [_("Quaoar","cosmos_bodies")],
            "Steins": [_("Steins","cosmos_bodies")],
            "Astr(é|e)e": [_("Astr(é|e)e","cosmos_bodies")],
            "Pholus": [_("Pholus","cosmos_bodies")],
            "Castalia": [_("Castalia","cosmos_bodies")],
            "Hector": [_("Hector","cosmos_bodies")],
            "Kl(é|e)opatra": [_("Kl(é|e)opatra","cosmos_bodies")],
            "Cruithne": [_("Cruithne","cosmos_bodies")],
            "Junon": [_("Junon","cosmos_bodies")],
            "Hygie": [_("Hygie","cosmos_bodies")],
            "Lutetia": [_("Lutetia","cosmos_bodies")],
            "Mathilde": [_("Mathilde","cosmos_bodies")],
            "Iris": [_("Iris","cosmos_bodies")],
            "Eros": [_("Eros","cosmos_bodies")],
            "Sedna": [_("Sedna","cosmos_bodies")],
            "Chariklo": [_("Chariklo","cosmos_bodies")],
            "Sylvia": [_("Sylvia","cosmos_bodies")],
            "Orcus": [_("Orcus","cosmos_bodies")],
            "Damocl(è|e)s": [_("Damocl(è|e)s","cosmos_bodies")],
            "Flore": [_("Flore","cosmos_bodies")],
            "Chiron": [_("Chiron","cosmos_bodies")],
            "Eurêka": [_("Eurêka","cosmos_bodies")],
            "Achille": [_("Achille","cosmos_bodies")],
            "Ixion": [_("Ixion","cosmos_bodies")],
            "Shoemaker-Levy 9": [_("Shoemaker-Levy 9","cosmos_bodies")],
            "M(é|e)tis": [_("M(é|e)tis","cosmos_bodies")],
            "Nessus": [_("Nessus","cosmos_bodies")],
            "Itokawa": [_("Itokawa","cosmos_bodies")],
            "Hylonome": [_("Hylonome","cosmos_bodies")],
            "Eug(é|e)ni(e|a)": [_("Eug(é|e)ni(e|a)","cosmos_bodies")],
            "2006 SQ372": [_("2006 SQ372","cosmos_bodies")],
            "Pallas": [_("Pallas","cosmos_bodies")],
            "Asbolus": [_("Asbolus","cosmos_bodies")],
            "Varuna": [_("Varuna","cosmos_bodies")],
            "Vesta": [_("Vesta","cosmos_bodies")],
            "Ida": [_("Ida","cosmos_bodies")],
            "Hyakutake": [_("Hyakutake","cosmos_bodies")],
            "Gaspra": [_("Gaspra","cosmos_bodies")],
            "1992 QB1": [_("1992 QB1","cosmos_bodies")],
            "Halley": [_("Halley","cosmos_bodies")],
            "Le Soleil": [_("Sun","cosmos_bodies")],
            "(486958) 2014 MU69": [_("Ultima Thule","cosmos_bodies")],
            "B(é|e)nou": [_("B(é|e)nou","cosmos_bodies")]
        }
    }
};